### ISSUE TITLE
Errors encountered when generated with a new app name

### ISSUE THREAD

**Issue by micahstubbs** [RailsApps/rails3-mongoid-omniauth#31]
I appreciate the tutorial - I was able to successfully generate the app using this command:

`$ rails new rails3-mongoid-omniauth -m https://raw.github.com/RailsApps/rails-composer/master/composer.rb -T -O`

however, when I change the app name to anything other than `rails3-mongoid-omniauth` I encounter errors.

**Comment by micahstubbs** [comment]
here is the most recent error block, starting with the most recent command:

```
      remove    app/controllers/users_controller.rb
/Users/m/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/net/http.rb:763:in `initialize':     getaddrinfo: nodename nor servname provided, or not known (SocketError)
    from /Users/m/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/net/http.rb:763:in `open'
    from /Users/m/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/net/http.rb:763:in `block in     connect'
    from /Users/m/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/timeout.rb:55:in `timeout'
    from /Users/m/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/timeout.rb:100:in `timeout'
    from /Users/m/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/net/http.rb:763:in `connect'
    from /Users/m/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/net/http.rb:756:in `do_start'
    from /Users/m/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/net/http.rb:745:in `start'
    from /Users/m/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/open-uri.rb:306:in `open_http'
    from /Users/m/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/open-uri.rb:775:in `buffer_open'
    from /Users/m/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/open-uri.rb:203:in `block in     open_loop'
    from /Users/m/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/open-uri.rb:201:in `catch'
    from /Users/m/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/open-uri.rb:201:in `open_loop'
    from /Users/m/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/open-uri.rb:146:in `open_uri'
    from /Users/m/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/open-uri.rb:677:in `open'
    from /Users/m/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/open-uri.rb:33:in `open'
    from /Users/m/.rvm/gems/ruby-1.9.3-p429@rails3tutorial2ndEd/gems/thor-0.18.    1/lib/thor/actions/file_manipulation.rb:83:in `get'
    from https://raw.github.com/RailsApps/rails-composer/master/composer.rb:200:in     `copy_from_repo'
    from https://raw.github.com/RailsApps/rails-composer/master/composer.rb:1581:in `block     in apply'
    from https://raw.github.com/RailsApps/rails-composer/master/composer.rb:2573:in `call'
    from https://raw.github.com/RailsApps/rails-composer/master/composer.rb:2573:in `block     in apply'
    from https://raw.github.com/RailsApps/rails-composer/master/composer.rb:2573:in `each'
    from https://raw.github.com/RailsApps/rails-composer/master/composer.rb:2573:in `apply'
    from /Users/m/.rvm/gems/ruby-1.9.3-p429@rails3tutorial2ndEd/gems/thor-0.18.    1/lib/thor/actions.rb:221:in `instance_eval'
    from /Users/m/.rvm/gems/ruby-1.9.3-p429@rails3tutorial2ndEd/gems/thor-0.18.    1/lib/thor/actions.rb:221:in `apply'
    from /Users/m/.rvm/gems/ruby-1.9.3-p429@rails3tutorial2ndEd/gems/railties-3.2.    13/lib/rails/generators/app_base.rb:109:in `apply_rails_template'
    from (eval):1:in `apply_rails_template'
    from /Users/m/.rvm/gems/ruby-1.9.3-p429@rails3tutorial2ndEd/gems/thor-0.18.    1/lib/thor/command.rb:27:in `run'
    from /Users/m/.rvm/gems/ruby-1.9.3-p429@rails3tutorial2ndEd/gems/thor-0.18.    1/lib/thor/invocation.rb:120:in `invoke_command'
    from /Users/m/.rvm/gems/ruby-1.9.3-p429@rails3tutorial2ndEd/gems/thor-0.18.    1/lib/thor/invocation.rb:127:in `block in invoke_all'
    from /Users/m/.rvm/gems/ruby-1.9.3-p429@rails3tutorial2ndEd/gems/thor-0.18.    1/lib/thor/invocation.rb:127:in `each'
    from /Users/m/.rvm/gems/ruby-1.9.3-p429@rails3tutorial2ndEd/gems/thor-0.18.    1/lib/thor/invocation.rb:127:in `map'
    from /Users/m/.rvm/gems/ruby-1.9.3-p429@rails3tutorial2ndEd/gems/thor-0.18.    1/lib/thor/invocation.rb:127:in `invoke_all'
    from /Users/m/.rvm/gems/ruby-1.9.3-p429@rails3tutorial2ndEd/gems/thor-0.18.    1/lib/thor/group.rb:233:in `dispatch'
    from /Users/m/.rvm/gems/ruby-1.9.3-p429@rails3tutorial2ndEd/gems/thor-0.18.    1/lib/thor/base.rb:439:in `start'
    from /Users/m/.rvm/gems/ruby-1.9.3-p429@rails3tutorial2ndEd/gems/railties-3.2.    13/lib/rails/commands/application.rb:38:in `<top (required)>'
    from /Users/m/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/site_ruby/1.9.    1/rubygems/custom_require.rb:36:in `require'
    from /Users/m/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/site_ruby/1.9.    1/rubygems/custom_require.rb:36:in `require'
    from /Users/m/.rvm/gems/ruby-1.9.3-p429@rails3tutorial2ndEd/gems/railties-3.2.    13/lib/rails/cli.rb:15:in `<top (required)>'
    from /Users/m/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/site_ruby/1.9.    1/rubygems/custom_require.rb:36:in `require'
    from /Users/m/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/site_ruby/1.9.    1/rubygems/custom_require.rb:36:in `require'
    from /Users/m/.rvm/gems/ruby-1.9.3-p429@rails3tutorial2ndEd/gems/railties-3.2.    13/bin/rails:7:in `<top (required)>'
    from /Users/m/.rvm/gems/ruby-1.9.3-p429@rails3tutorial2ndEd/bin/rails:19:in `load'
    from /Users/m/.rvm/gems/ruby-1.9.3-p429@rails3tutorial2ndEd/bin/rails:19:in `<main>'
    from /Users/m/.rvm/gems/ruby-1.9.3-    p429@rails3tutorial2ndEd/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/m/.rvm/gems/ruby-1.9.3-    p429@rails3tutorial2ndEd/bin/ruby_noexec_wrapper:14:in `<main>'    
```
